# Generated by Django 3.2.8 on 2021-12-12 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='products.origin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr', to='products.seller'),
        ),
    ]
