# Generated by Django 3.2.8 on 2021-12-13 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_auto_20211213_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='origin',
            name='origin_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.origin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.seller'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
